parameters:
    stubber:
    stubber.environment: prod
    stubber.debug: false
    stubber.root_dir: %kernel.root_dir%/../stubber

services:
    stubber.server:
        class:     Stubber\Server

    stubber.symfony2application:
        class:     Stubber\Bundle\Application\Symfony2Application
        arguments: [@stubber.server]
